In [1]:
class Employee:
    num_employees = 0  # Class variable to count the number of Employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.num_employees += 1

    def average_salary(self, employees):
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees) if len(employees) > 0 else 0

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

# Create instances of Employee and FulltimeEmployee
employee1 = Employee("Lakshmi", "Family Lakshmi", 80000, "Manager")
employee2 = Employee("Ankitha", "Family Ankitha", 80000, "HR")

fulltime_employee1 = FulltimeEmployee("Nilesh", "Family Nilesh", 90000, "IT")

# Call member functions
employees_list = [employee1, employee2, fulltime_employee1]
avg_salary = employee1.average_salary(employees_list)

print(f"Total number of employees: {Employee.num_employees}")
print(f"Average salary of employees: {avg_salary}")


Total number of employees: 3
Average salary of employees: 83333.33333333333


In [2]:
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

# Reshape the array to 4 by 5
reshaped_array = random_vector.reshape(4, 5)

# Replace the max in each row by 0 along axis=1
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Original array:")
print(random_vector)
print("\nReshaped array:")
print(reshaped_array)


Original array:
[ 6.38737752  4.0446485  16.42472388  0.          1.07066676  0.
  4.50495011  2.25052736  6.52379036 10.31269162 15.40293418 17.97733671
 12.13203833 17.14852608  0.          0.          5.17263824 13.19926304
  6.04215902 14.94539742]

Reshaped array:
[[ 6.38737752  4.0446485  16.42472388  0.          1.07066676]
 [ 0.          4.50495011  2.25052736  6.52379036 10.31269162]
 [15.40293418 17.97733671 12.13203833 17.14852608  0.        ]
 [ 0.          5.17263824 13.19926304  6.04215902 14.94539742]]
